defmodule Phoenix2FAWeb.UserKeyHTML do
  use Phoenix2FAWeb, :html

  embed_templates "user_key_html/*"

  @doc """
  Renders a user_key form.
  """
  attr :action, :string, required: true
  attr :changeset, Ecto.Changeset

  def user_key_form(assigns)

  @doc """
  Renders the u2f key registration form
  """
  attr :current_user, :any, required: true, doc: "User who is registering a new key"
  attr :challenge, :map, required: true, doc: "challenge generated by Wax"
  attr :cred_ids, :list, required: true, doc: "A list of the users user_key's cred_ids"

  def u2f_registration_form(assigns)

  @doc """
  Renders the u2f key authentication form
  """
  attr :user_id, :any, required: true, doc: "User who is trying to authenticate"
  attr :challenge, :map, required: true, doc: "challenge generated by Wax"
  attr :cred_ids, :list, required: true, doc: "A list of the users user_key's cred_ids"

  def u2f_authentication_form(assigns)

  @doc """
  U2f Javascript helpers
  """
  def javascript_helper_functions(assigns)

  @doc """
  TOTP registration form
  """
  attr :qr_code_uri, :string, required: true, doc: "String used to display the QR code"
  attr :current_user, :map, required: true

  def totp_registration_form(assigns)
end
