# fly.toml app configuration file generated for phoenix-2fa on 2023-06-10T20:01:11-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "phoenix-2fa"
primary_region = "ewr"
kill_signal = "SIGTERM"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "phoenix-2fa.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
